### ISSUE TITLE
CheckHum 00DefaultPage

### ISSUE THREAD

**Issue by OuYangPlane** [Suprcode/mir2-database#4]

**Comment by OuYangPlane** [comment]
![`P `LXQ(`OZ75N1S6_55EL9](https://user-images.githubusercontent.com/106395089/181905490-554883eb-c7ad-46bc-b5a6-ed484850eaea.png)

**Comment by JevLOMCN** [comment]
Waht issue are you logging? the missing maps or the 00Default error?

**Comment by OuYangPlane** [comment]
> 

I just compiled the latest code, downloaded the latest database, downloaded the latest client, and put the database into the latest server causing this problem

**Comment by JevLOMCN** [comment]
The 00Default is now fixed in the latest source code.

**Comment by JevLOMCN** [comment]
Fixed and will come out in the latest patch that will release later today (02/08/22)
